# src/main/resources/application.properties

# Google Gemini API \uD0A4
gemini.api.key=AIzaSyDY-8aFtsgbgq-ca_3dfKXfIvl4SY1BqjI


# Google Cloud Project \uC124\uC815 (Vertex AI \uB77C\uC774\uBE0C\uB7EC\uB9AC \uBC29\uC2DD \uC0AC\uC6A9 \uC2DC)
gcp.project.id=your-gcp-project-id
gcp.project.location=asia-northeast3
gemini.model.name=gemini-1.5-pro-preview-0409

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
upload.path=C:/dev/upload